#environment:
#  - MAIL_PASSWORD=112jmksT

services:
  app:
    image: nicdkim/itdat-namewallet
    container_name: itdat-namewallet
    environment:
      - MAIL_PASSWORD=112jmksT
      - JWT_SECRET_KEY=57c3aff4146e0ef2d7e742613adfc85cef9a4d258213d749dcb1b4a5435b8a22
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
    ports:
      - "8082:8082"
    networks:
      - default
networks:
  default:
    driver: bridge
