services:
  app:
    image: nicdkim/itdat-namewallet
    container_name: itdat-namewallet
    environment:
      - MAIL_PASSWORD=112jmksT
      - JWT_SECRET_KEY=57c3aff4146e0ef2d7e742613adfc85cef9a4d258213d749dcb1b4a5435b8a22
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/itdat
      - SPRING_DATASOURCE_USERNAME=gangnam
      - SPRING_DATASOURCE_PASSWORD=gangnam
    ports:
      - "8082:8082"
    networks:
      - default
    depends_on:
      - db
    volumes:
      - ./uploads:/logos
      - ./uploads:/board

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itdat
      MYSQL_USER: gangnam
      MYSQL_PASSWORD: gangnam
    ports:
      - "3306:3306"
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge
