spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://198.168.0.47:3306/itdat
    username: gangnam
    password: gangnam

# localhost 를 찾지 못한다. 가상환경 자기 자신을 의미하기 때문에