server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 스키마 검증만(validate)
    properties:
      hibernate:
        format_sql: false  # SQL 포맷 비활성화

  naver:
    works:
      client-id: ${NAVER_WORKS_CLIENT_ID}
      client-secret: ${NAVER_WORKS_CLIENT_SECRET}
      domain-id: ${NAVER_WORKS_DOMAIN_ID}
      base-url: ${NAVER_WORKS_BASE_URL}
      redirect-url: ${NAVER_WORKS_REDIRECT_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

cors:
  allowed-origins:
  - https://www.itdat.store
  - http://localhost:3000
  - https://namewallet.store:6816

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 86400000
