server:
  ssl:
    enabled: false
  address: 0.0.0.0
  port: 8000


spring:
  web:
    resources:
      static-locations: classpath:/templates/
  config:
    import: "classpath:application-db.yml"
  profiles:
    active: dev  # 기본 프로파일을 개발 환경(dev)으로 설정

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${app.base-url}/oauth/callback/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "${app.base-url}/oauth/callback/naver"
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "${app.base-url}/oauth/callback/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.email
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  naver:
    works:
      client-id: ${NAVER_WORKS_CLIENT_ID}
      client-secret: ${NAVER_WORKS_CLIENT_SECRET}
      domain-id: ${NAVER_WORKS_DOMAIN_ID}
      base-url: ${NAVER_WORKS_BASE_URL}
      redirect-url: ${NAVER_WORKS_REDIRECT_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: INFO

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 환경변수 등록 필요
  expiration: 86400000