server:
  ssl:
    enabled: false
#  port: 8082
  port: 8001
#  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  config:
    import: "classpath:application-db.yml"
  profiles:
    active: dev  # 기본 프로파일을 개발 환경(dev)으로 설정
  web:
    resources:
      static-locations: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB # 업로드할 파일의 최대 크기
      max-request-size: 10MB # 요청의 최대 크기 (파일 크기 + 기타 데이터 포함)

  security:
    ignored: /templates/** # Spring Security가 이 경로를 무시하도록 설정
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${app.base-url}/api/oauth/callback/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "${app.base-url}/oauth/callback/naver"
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "${app.base-url}/oauth/callback/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.email
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  naver:
    works:
      client-id: ${NAVER_WORKS_CLIENT_ID}
      client-secret: ${NAVER_WORKS_CLIENT_SECRET}
      domain-id: ${NAVER_WORKS_DOMAIN_ID}
      base-url: ${NAVER_WORKS_BASE_URL}
      redirect-url: ${NAVER_WORKS_REDIRECT_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 환경변수 등록 필요
  expiration: 86400000

file:
  upload-dir: "C:\\uploads"  # Windows 경로에서 백슬래시 두 개 사용
  expiration: 86400000

