spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # 개발 환경에서는 스키마 업데이트 허용
    properties:
      hibernate:
        format_sql: true  # SQL 포맷 활성화

  naver:
    works:
      client-id: RFqdC7PF7PVsvVnoN1Yy
      client-secret: uOtFkIpZS6
      domain-id: 300183791
      base-url: https://apis.worksmobile.com
      redirect-url: http://localhost:3000/callback


#  mail:
#    host: smtp.worksmail.com
#    port: 587
#    username: noreply@www.itdat.store
#    password: ${MAIL_PASSWORD}  # 시스템 환경 변수로 관리
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  mail:
    host: smtp.worksmobile.com
    port: 587
    username: ww.24575@www.itdat.store
    password: NZVvL9wTvC9A
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

cors:
  allowed-origins: http://localhost:3000
