server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 스키마 검증만
    properties:
      hibernate:
        format_sql: false  # SQL 포맷 비활성화

logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

cors:
  allowed-origins: https://www.itdat.store
