server:
  ssl:
    enabled: false
  port: 8082
  address: 0.0.0.0

spring:
  config:
    import: "classpath:application-db.yml"
  profiles:
    active: dev  # 기본 프로파일을 개발 환경(dev)으로 설정

  naver:
    works:
      client-id: RFqdC7PF7PVsvVnoN1Yy
      client-secret: uOtFkIpZS6
      domain-id: 300183791
      base-url: https://apis.worksmobile.com
      redirect-url: http://localhost:3000/callback



  mail:
    host: smtp.worksmobile.com
    port: 587
    username: ww.24575@www.itdat.store
    password: NZVvL9wTvC9A
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: INFO

jwt:
  secret-key: ${JWT_SECRET_KEY} # 환경변수 등록 필요
  expiration: 86400000

file:
  upload-dir: "C:\\uploads"  # Windows 경로에서 백슬래시 두 개 사용

