server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 스키마 검증만
    properties:
      hibernate:
        format_sql: false  # SQL 포맷 비활성화

  naver:
    works:
      client-id: RFqdC7PF7PVsvVnoN1Yy
      client-secret: uOtFkIpZS6
      domain-id: 300183791
      base-url: https://apis.worksmobile.com
      redirect-url: https://www.itdat.store/callback


#  mail:
#    host: smtp.worksmail.com
#    port: 587
#    username: noreply@www.itdat.store
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  mail:
    host: smtp.worksmobile.com
    port: 587
    username: ww.24575@www.itdat.store
    password: NZVvL9wTvC9A
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

cors:
  allowed-origins: https://www.itdat.store

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 86400000
